-- ==============================================================================
-- NFC Mess Food Tracker - Supabase PostgreSQL Schema & Seed Script
-- ==============================================================================

-- 1. Create Tables

-- Students Table
CREATE TABLE IF NOT EXISTS students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roll_number TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  card_id TEXT UNIQUE NOT NULL,
  department TEXT NOT NULL,
  year INTEGER NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Meal Records Table
CREATE TABLE IF NOT EXISTS meal_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  meal_type TEXT NOT NULL,
  meal_date DATE NOT NULL,
  scanned_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_student_meal_date UNIQUE (student_id, meal_type, meal_date)
);

-- Settings Table (Key-Value)
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Users Table (Admin authentication)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Indexes for Performance & Queries
CREATE INDEX IF NOT EXISTS idx_students_card_id ON students(card_id);
CREATE INDEX IF NOT EXISTS idx_students_roll_number ON students(roll_number);
CREATE INDEX IF NOT EXISTS idx_meal_records_meal_date ON meal_records(meal_date);
CREATE INDEX IF NOT EXISTS idx_meal_records_student_id ON meal_records(student_id);

-- 3. Row Level Security (RLS) & Security Policies
-- Protects database tables from unauthorized direct PostgREST/browser access.
-- All client interactions go through Netlify Functions with SUPABASE_SERVICE_ROLE_KEY.
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Allow API access (supports both service_role key and anon/publishable key)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'students' AND policyname = 'api_all_students'
  ) THEN
    CREATE POLICY api_all_students ON students FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'meal_records' AND policyname = 'api_all_meal_records'
  ) THEN
    CREATE POLICY api_all_meal_records ON meal_records FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'settings' AND policyname = 'api_all_settings'
  ) THEN
    CREATE POLICY api_all_settings ON settings FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'users' AND policyname = 'api_all_users'
  ) THEN
    CREATE POLICY api_all_users ON users FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);
  END IF;
END $$;

-- 4. Seed Default Settings
INSERT INTO settings (key, value)
VALUES
  ('breakfast_start', '07:00'),
  ('breakfast_end', '10:00'),
  ('snack1_start', '10:30'),
  ('snack1_end', '11:30'),
  ('lunch_start', '12:00'),
  ('lunch_end', '15:00'),
  ('snack2_start', '16:00'),
  ('snack2_end', '17:30'),
  ('dinner_start', '19:00'),
  ('dinner_end', '22:00'),
  ('snack3_start', '22:00'),
  ('snack3_end', '23:30'),
  ('mess_name', 'Central Hostel Mess'),
  ('total_capacity', '200')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- 5. Seed Default Admin User (Password: admin123)
-- Valid bcrypt hash generated with bcryptjs for 'admin123' (10 rounds)
INSERT INTO users (email, password_hash, name, role)
VALUES (
  'admin@mess.edu',
  '$2a$10$.67M90L4dMKHmPsR7u.bMu5RIEm5DMV6M41/G6siLdWIzIvG3gikK',
  'Mess Superintendent',
  'admin'
)
ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash;

-- 6. Seed 20 Sample Students
INSERT INTO students (roll_number, name, card_id, department, year, active)
VALUES
  ('23AK1A3218', 'Karthikeya R', 'NFC-23CSE1001', 'CSD', 4, true),
  ('23CSE1002', 'Priya Sharma', 'NFC-23CSE1002', 'CSE', 3, true),
  ('23ECE1003', 'Arjun Reddy', 'NFC-23CSE1003', 'ECE', 2, true),
  ('23ECE1004', 'Ananya Roy', 'NFC-23CSE1004', 'ECE', 2, true),
  ('23ME1005', 'Sai Teja', 'NFC-23CSE1005', 'MECH', 4, true),
  ('23EEE1006', 'Aditya Verma', 'NFC-23CSE1006', 'EEE', 1, true),
  ('23CIV1007', 'Sneha Patel', 'NFC-23CSE1007', 'CIVIL', 3, true),
  ('23CSE1008', 'Rohan Gupta', 'NFC-23CSE1008', 'CSE', 2, true),
  ('23IT1009', 'Kavya Nair', 'NFC-23CSE1009', 'IT', 4, true),
  ('23ME1010', 'Vikram Singh', 'NFC-23CSE1010', 'MECH', 1, true),
  ('23CSE1011', 'Meera Deshmukh', 'NFC-23CSE1011', 'CSE', 3, true),
  ('23ECE1012', 'Karthik Raja', 'NFC-23CSE1012', 'ECE', 2, true),
  ('23IT1013', 'Divya Iyer', 'NFC-23CSE1013', 'IT', 3, true),
  ('23CIV1014', 'Aman Khan', 'NFC-23CSE1014', 'CIVIL', 4, true),
  ('23EEE1015', 'Pooja Bhat', 'NFC-23CSE1015', 'EEE', 2, true),
  ('23CSE1016', 'Siddharth Joshi', 'NFC-23CSE1016', 'CSE', 1, true),
  ('23ECE1017', 'Tanvi Sen', 'NFC-23CSE1017', 'ECE', 3, true),
  ('23ME1018', 'Varun Rao', 'NFC-23CSE1018', 'MECH', 2, true),
  ('23IT1019', 'Neha Das', 'NFC-23CSE1019', 'IT', 1, true),
  ('23CIV1020', 'Yash Vardhan', 'NFC-23CSE1020', 'CIVIL', 4, true)
ON CONFLICT (roll_number) DO NOTHING;

-- 7. Seed Sample Meal Records (past days & today)
DO $$
DECLARE
  rec RECORD;
  today_date DATE := CURRENT_DATE;
  yesterday_date DATE := CURRENT_DATE - INTERVAL '1 day';
  prev_date DATE := CURRENT_DATE - INTERVAL '2 days';
  idx INTEGER := 0;
BEGIN
  FOR rec IN SELECT id FROM students ORDER BY id ASC LOOP
    idx := idx + 1;
    
    -- Two days ago: ~85% attendance
    IF idx % 10 != 0 THEN
      INSERT INTO meal_records (student_id, meal_type, meal_date, scanned_at)
      VALUES 
        (rec.id, 'Breakfast', prev_date, (prev_date::text || ' 08:15:00+00')::TIMESTAMPTZ),
        (rec.id, 'Lunch', prev_date, (prev_date::text || ' 13:20:00+00')::TIMESTAMPTZ),
        (rec.id, 'Dinner', prev_date, (prev_date::text || ' 20:30:00+00')::TIMESTAMPTZ)
      ON CONFLICT (student_id, meal_type, meal_date) DO NOTHING;
    END IF;

    -- Yesterday: ~85% attendance
    IF idx % 8 != 0 THEN
      INSERT INTO meal_records (student_id, meal_type, meal_date, scanned_at)
      VALUES 
        (rec.id, 'Breakfast', yesterday_date, (yesterday_date::text || ' 08:25:00+00')::TIMESTAMPTZ),
        (rec.id, 'Lunch', yesterday_date, (yesterday_date::text || ' 13:15:00+00')::TIMESTAMPTZ),
        (rec.id, 'Dinner', yesterday_date, (yesterday_date::text || ' 20:10:00+00')::TIMESTAMPTZ)
      ON CONFLICT (student_id, meal_type, meal_date) DO NOTHING;
    END IF;

    -- Today: Breakfast (18), Lunch (15), Snack 1 (14), Dinner (10)
    IF idx <= 18 THEN
      INSERT INTO meal_records (student_id, meal_type, meal_date, scanned_at)
      VALUES (rec.id, 'Breakfast', today_date, (today_date::text || ' 08:20:00+00')::TIMESTAMPTZ)
      ON CONFLICT (student_id, meal_type, meal_date) DO NOTHING;
    END IF;

    IF idx <= 15 THEN
      INSERT INTO meal_records (student_id, meal_type, meal_date, scanned_at)
      VALUES (rec.id, 'Lunch', today_date, (today_date::text || ' 13:10:00+00')::TIMESTAMPTZ)
      ON CONFLICT (student_id, meal_type, meal_date) DO NOTHING;
    END IF;

    IF idx <= 14 THEN
      INSERT INTO meal_records (student_id, meal_type, meal_date, scanned_at)
      VALUES (rec.id, 'Snack 1', today_date, (today_date::text || ' 11:00:00+00')::TIMESTAMPTZ)
      ON CONFLICT (student_id, meal_type, meal_date) DO NOTHING;
    END IF;

    IF idx <= 10 THEN
      INSERT INTO meal_records (student_id, meal_type, meal_date, scanned_at)
      VALUES (rec.id, 'Dinner', today_date, (today_date::text || ' 20:15:00+00')::TIMESTAMPTZ)
      ON CONFLICT (student_id, meal_type, meal_date) DO NOTHING;
    END IF;
  END LOOP;
END $$;
