-- ==============================================================================
-- NFC Mess Food Tracker - Supabase PostgreSQL Schema & Seed Script
-- ==============================================================================

-- 1. Create Tables

-- Students Table
CREATE TABLE IF NOT EXISTS students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roll_number TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  card_id TEXT UNIQUE NOT NULL,
  department TEXT NOT NULL,
  year INTEGER NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Meal Records Table
CREATE TABLE IF NOT EXISTS meal_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  meal_type TEXT NOT NULL,
  meal_date DATE NOT NULL,
  scanned_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_student_meal_date UNIQUE (student_id, meal_type, meal_date)
);

-- Settings Table (Key-Value)
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Users Table (Admin authentication)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Indexes for Performance & Queries
CREATE INDEX IF NOT EXISTS idx_students_card_id ON students(card_id);
CREATE INDEX IF NOT EXISTS idx_students_roll_number ON students(roll_number);
CREATE INDEX IF NOT EXISTS idx_meal_records_meal_date ON meal_records(meal_date);
CREATE INDEX IF NOT EXISTS idx_meal_records_student_id ON meal_records(student_id);

-- 3. Row Level Security (RLS) & Security Policies
-- Protects database tables from unauthorized direct PostgREST/browser access.
-- All client interactions go through Netlify Functions with SUPABASE_SERVICE_ROLE_KEY.
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Allow API access (supports both service_role key and anon/publishable key)
DO $$
BEGIN
  DROP POLICY IF EXISTS service_role_all_students ON students;
  DROP POLICY IF EXISTS api_all_students ON students;
  CREATE POLICY api_all_students ON students FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);

  DROP POLICY IF EXISTS service_role_all_meal_records ON meal_records;
  DROP POLICY IF EXISTS api_all_meal_records ON meal_records;
  CREATE POLICY api_all_meal_records ON meal_records FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);

  DROP POLICY IF EXISTS service_role_all_settings ON settings;
  DROP POLICY IF EXISTS api_all_settings ON settings;
  CREATE POLICY api_all_settings ON settings FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);

  DROP POLICY IF EXISTS service_role_all_users ON users;
  DROP POLICY IF EXISTS api_all_users ON users;
  CREATE POLICY api_all_users ON users FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);
END $$;

-- 4. Seed Default Settings
INSERT INTO settings (key, value)
VALUES
  ('snack_start', '10:30'),
  ('snack_end', '11:30'),
  ('meal_start', '19:00'),
  ('meal_end', '22:00'),
  ('mess_name', 'NEXUS Fest 2026'),
  ('total_capacity', '65')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- 5. Seed Default Admin User (Password: admin123)
INSERT INTO users (email, password_hash, name, role)
VALUES (
  'admin@mess.edu',
  '$2a$10$7iHVjqWvLO3I3Z771MIF8OlWH5RMnFHqpwvYTaqn3oQaAMLjwxTLu',
  'NEXUS Admin',
  'admin'
)
ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash;

-- 6. Seed 65 Official NEXUS Participants (IV-I CSE Data Science)
INSERT INTO students (roll_number, name, card_id, department, year, active)
VALUES
  ('23AK1A3201', 'ARSHIYA K', '23AK1A3201', 'CSD', 4, true),
  ('23AK1A3202', 'ARSHIYA KASALA', '23AK1A3202', 'CSD', 4, true),
  ('23AK1A3203', 'BHARATH R', '23AK1A3203', 'CSD', 4, true),
  ('23AK1A3204', 'CHAITHANYA K', '23AK1A3204', 'CSD', 4, true),
  ('23AK1A3205', 'CHETHAN KUMAR REDDY M', '23AK1A3205', 'CSD', 4, true),
  ('23AK1A3206', 'CYPRIAN A', '23AK1A3206', 'CSD', 4, true),
  ('23AK1A3207', 'DILEEP K', '23AK1A3207', 'CSD', 4, true),
  ('23AK1A3208', 'DINESH V', '23AK1A3208', 'CSD', 4, true),
  ('23AK1A3209', 'DIVYA SRI S', '23AK1A3209', 'CSD', 4, true),
  ('23AK1A3210', 'GIRISH K', '23AK1A3210', 'CSD', 4, true),
  ('23AK1A3211', 'GOWTHAMI P', '23AK1A3211', 'CSD', 4, true),
  ('23AK1A3212', 'GUNAMALIKA M', '23AK1A3212', 'CSD', 4, true),
  ('23AK1A3213', 'HARI K', '23AK1A3213', 'CSD', 4, true),
  ('23AK1A3214', 'HARSHA PRIYA S', '23AK1A3214', 'CSD', 4, true),
  ('23AK1A3215', 'HEMA SAI M', '23AK1A3215', 'CSD', 4, true),
  ('23AK1A3216', 'HITHESH M', '23AK1A3216', 'CSD', 4, true),
  ('23AK1A3217', 'JOSHNA A', '23AK1A3217', 'CSD', 4, true),
  ('23AK1A3218', 'Karthikeya R', '23AK1A3218', 'CSD', 4, true),
  ('23AK1A3219', 'KAVITHA K', '23AK1A3219', 'CSD', 4, true),
  ('23AK1A3220', 'KEERTHI R', '23AK1A3220', 'CSD', 4, true),
  ('23AK1A3221', 'KEERTHI REDDY K', '23AK1A3221', 'CSD', 4, true),
  ('23AK1A3222', 'KETHAN A', '23AK1A3222', 'CSD', 4, true),
  ('23AK1A3223', 'LIKHETA A', '23AK1A3223', 'CSD', 4, true),
  ('23AK1A3224', 'LIKITHA N', '23AK1A3224', 'CSD', 4, true),
  ('23AK1A3225', 'MANOJ KUMAR K', '23AK1A3225', 'CSD', 4, true),
  ('23AK1A3226', 'MOUNIKA K', '23AK1A3226', 'CSD', 4, true),
  ('23AK1A3227', 'MOUNIKA P', '23AK1A3227', 'CSD', 4, true),
  ('23AK1A3228', 'MUNIRAJA K', '23AK1A3228', 'CSD', 4, true),
  ('23AK1A3229', 'NARAYANA P', '23AK1A3229', 'CSD', 4, true),
  ('23AK1A3230', 'NAVEEN J', '23AK1A3230', 'CSD', 4, true),
  ('23AK1A3231', 'NAZIYA BANU SHAIK', '23AK1A3231', 'CSD', 4, true),
  ('23AK1A3232', 'PRAJWAL K', '23AK1A3232', 'CSD', 4, true),
  ('23AK1A3233', 'PRASHANTH K', '23AK1A3233', 'CSD', 4, true),
  ('23AK1A3234', 'PRATHIBHA E', '23AK1A3234', 'CSD', 4, true),
  ('23AK1A3235', 'RAJASEKHAR T', '23AK1A3235', 'CSD', 4, true),
  ('23AK1A3236', 'RAJU B', '23AK1A3236', 'CSD', 4, true),
  ('23AK1A3237', 'RAKESH K', '23AK1A3237', 'CSD', 4, true),
  ('23AK1A3238', 'RAVI TEJA K', '23AK1A3238', 'CSD', 4, true),
  ('23AK1A3239', 'REVATHI V', '23AK1A3239', 'CSD', 4, true),
  ('23AK1A3240', 'ROHITHA B', '23AK1A3240', 'CSD', 4, true),
  ('23AK1A3241', 'RUPASREE J', '23AK1A3241', 'CSD', 4, true),
  ('23AK1A3242', 'SALOMAN H', '23AK1A3242', 'CSD', 4, true),
  ('23AK1A3243', 'SRAVANTHI D', '23AK1A3243', 'CSD', 4, true),
  ('23AK1A3244', 'SREENADH K', '23AK1A3244', 'CSD', 4, true),
  ('23AK1A3245', 'SUMA LATHA K', '23AK1A3245', 'CSD', 4, true),
  ('23AK1A3246', 'SUMITH M', '23AK1A3246', 'CSD', 4, true),
  ('23AK1A3247', 'SWATHI G', '23AK1A3247', 'CSD', 4, true),
  ('23AK1A3248', 'SWETHA N', '23AK1A3248', 'CSD', 4, true),
  ('23AK1A3249', 'TEJA KIRAN B', '23AK1A3249', 'CSD', 4, true),
  ('23AK1A3250', 'THANUSREE P', '23AK1A3250', 'CSD', 4, true),
  ('23AK1A3251', 'TRIVEEN KUMAR J', '23AK1A3251', 'CSD', 4, true),
  ('23AK1A3252', 'VAISHNAVI C', '23AK1A3252', 'CSD', 4, true),
  ('23AK1A3254', 'VASU P', '23AK1A3254', 'CSD', 4, true),
  ('23AK1A3255', 'VINEELA G', '23AK1A3255', 'CSD', 4, true),
  ('23AK1A3256', 'VINITHA T', '23AK1A3256', 'CSD', 4, true),
  ('23AK1A3257', 'VINODH KUMAR S', '23AK1A3257', 'CSD', 4, true),
  ('23AK1A3258', 'YASHASWINI S', '23AK1A3258', 'CSD', 4, true),
  ('23AK1A3259', 'YOGA SAI KUMAR S', '23AK1A3259', 'CSD', 4, true),
  ('23AK1A3260', 'YUGANDHAR K', '23AK1A3260', 'CSD', 4, true),
  ('24AK5A3201', 'DWARAKANATH M', '24AK5A3201', 'CSD', 4, true),
  ('24AK5A3202', 'GAYATHRI K', '24AK5A3202', 'CSD', 4, true),
  ('24AK5A3203', 'LOKESH REDDY D', '24AK5A3203', 'CSD', 4, true),
  ('24AK5A3204', 'MAMATHA K', '24AK5A3204', 'CSD', 4, true),
  ('24AK5A3205', 'PHANEENDRA NAIDU G', '24AK5A3205', 'CSD', 4, true),
  ('24AK5A3206', 'VEDANTHESHWAR M', '24AK5A3206', 'CSD', 4, true)
ON CONFLICT (roll_number) DO UPDATE SET
  name = EXCLUDED.name,
  card_id = EXCLUDED.card_id,
  department = EXCLUDED.department,
  year = EXCLUDED.year,
  active = EXCLUDED.active;

-- 7. Meal Records start completely clean (0 records) for the NEXUS Fest POC.
